<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="20" failed="1" total="45" passed="24">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="339264" started-at="2020-09-29T08:41:43Z" finished-at="2020-09-29T08:47:22Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="339264" started-at="2020-09-29T08:41:43Z" finished-at="2020-09-29T08:47:22Z">
      <class name="testcases.TestCompetition">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="set" is-config="true" duration-ms="1" started-at="2020-09-29T15:44:34Z" finished-at="2020-09-29T15:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="competitionNow()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="competitionNow" duration-ms="2585" started-at="2020-09-29T15:44:34Z" finished-at="2020-09-29T15:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- competitionNow -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:44:36Z" finished-at="2020-09-29T15:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="set" is-config="true" duration-ms="1" started-at="2020-09-29T15:44:36Z" finished-at="2020-09-29T15:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="competitionSoon()[pri:1, instance:testcases.TestCompetition@50fe837a]" name="competitionSoon" duration-ms="2582" started-at="2020-09-29T15:44:36Z" finished-at="2020-09-29T15:44:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- competitionSoon -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:44:39Z" finished-at="2020-09-29T15:44:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:44:39Z" finished-at="2020-09-29T15:44:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="competitionExpired()[pri:2, instance:testcases.TestCompetition@50fe837a]" name="competitionExpired" duration-ms="2178" started-at="2020-09-29T15:44:39Z" finished-at="2020-09-29T15:44:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- competitionExpired -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestCompetition@50fe837a]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:44:41Z" finished-at="2020-09-29T15:44:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestCompetition -->
      <class name="testcases.TestSearch">
        <test-method status="SKIP" signature="user(java.lang.String)[pri:0, instance:testcases.TestSearch@150ab4ed]" name="user" duration-ms="0" started-at="2020-09-29T15:42:12Z" data-provider="SearchUser" finished-at="2020-09-29T15:42:12Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestSearch.SearchUser(TestSearch.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestSearch@150ab4ed]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:42:12Z" finished-at="2020-09-29T15:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="userNotFound()[pri:1, instance:testcases.TestSearch@150ab4ed]" name="userNotFound" duration-ms="4332" started-at="2020-09-29T15:42:12Z" finished-at="2020-09-29T15:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userNotFound -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestSearch@150ab4ed]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:42:16Z" finished-at="2020-09-29T15:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="SKIP" signature="video(java.lang.String)[pri:2, instance:testcases.TestSearch@150ab4ed]" name="video" duration-ms="0" started-at="2020-09-29T15:42:16Z" data-provider="SearchVideo" finished-at="2020-09-29T15:42:16Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestSearch.SearchVideo(TestSearch.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- video -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestSearch@150ab4ed]" name="set" is-config="true" duration-ms="3" started-at="2020-09-29T15:42:16Z" finished-at="2020-09-29T15:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="videoNotFound()[pri:2, instance:testcases.TestSearch@150ab4ed]" name="videoNotFound" duration-ms="3386" started-at="2020-09-29T15:42:16Z" finished-at="2020-09-29T15:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- videoNotFound -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestSearch@150ab4ed]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:42:19Z" finished-at="2020-09-29T15:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestSearch -->
      <class name="testcases.TestUser">
        <test-method status="SKIP" signature="myProfile(java.lang.String, java.lang.String)[pri:0, instance:testcases.TestUser@5357c287]" name="myProfile" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="User" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestUser.User(TestUser.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myProfile -->
        <test-method status="SKIP" signature="otherUserVisitorToken(java.lang.String, java.lang.String)[pri:1, instance:testcases.TestUser@5357c287]" name="otherUserVisitorToken" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="User" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestUser.User(TestUser.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- otherUserVisitorToken -->
        <test-method status="SKIP" signature="otherUserTokenUser(java.lang.String, java.lang.String)[pri:2, instance:testcases.TestUser@5357c287]" name="otherUserTokenUser" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="User" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestUser.User(TestUser.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- otherUserTokenUser -->
      </class> <!-- testcases.TestUser -->
      <class name="testcases.TestEditUser">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestEditUser@a8c1f44]" name="set" is-config="true" duration-ms="1582" started-at="2020-09-29T15:41:43Z" finished-at="2020-09-29T15:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="postComment()[pri:0, instance:testcases.TestEditUser@a8c1f44]" name="postComment" duration-ms="26775" started-at="2020-09-29T15:41:45Z" finished-at="2020-09-29T15:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postComment -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestEditUser@a8c1f44]" name="down" is-config="true" duration-ms="5" started-at="2020-09-29T15:42:12Z" finished-at="2020-09-29T15:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestEditUser -->
      <class name="testcases.TestComment">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestComment@5ce33a58]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:46:36Z" finished-at="2020-09-29T15:46:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="postComment()[pri:0, instance:testcases.TestComment@5ce33a58]" name="postComment" duration-ms="13884" started-at="2020-09-29T15:46:36Z" finished-at="2020-09-29T15:46:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postComment -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestComment@5ce33a58]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:46:50Z" finished-at="2020-09-29T15:46:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestComment@5ce33a58]" name="set" is-config="true" duration-ms="3" started-at="2020-09-29T15:46:50Z" finished-at="2020-09-29T15:46:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="getComment()[pri:1, instance:testcases.TestComment@5ce33a58]" name="getComment" duration-ms="14711" started-at="2020-09-29T15:46:50Z" finished-at="2020-09-29T15:47:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getComment -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestComment@5ce33a58]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:47:05Z" finished-at="2020-09-29T15:47:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestComment -->
      <class name="testcases.TestHome">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestHome@78a287ed]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:47:05Z" finished-at="2020-09-29T15:47:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="getHomeCategory()[pri:0, instance:testcases.TestHome@78a287ed]" name="getHomeCategory" duration-ms="4300" started-at="2020-09-29T15:47:05Z" finished-at="2020-09-29T15:47:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getHomeCategory -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestHome@78a287ed]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:47:09Z" finished-at="2020-09-29T15:47:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestHome@78a287ed]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:47:09Z" finished-at="2020-09-29T15:47:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="getHomeByCompetition()[pri:1, instance:testcases.TestHome@78a287ed]" name="getHomeByCompetition" duration-ms="8487" started-at="2020-09-29T15:47:09Z" finished-at="2020-09-29T15:47:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getHomeByCompetition -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestHome@78a287ed]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:47:18Z" finished-at="2020-09-29T15:47:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestHome@78a287ed]" name="set" is-config="true" duration-ms="1" started-at="2020-09-29T15:47:18Z" finished-at="2020-09-29T15:47:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="getListCompetition()[pri:2, instance:testcases.TestHome@78a287ed]" name="getListCompetition" duration-ms="4690" started-at="2020-09-29T15:47:18Z" finished-at="2020-09-29T15:47:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListCompetition -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestHome@78a287ed]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:47:22Z" finished-at="2020-09-29T15:47:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestHome -->
      <class name="testcases.TestFollow">
        <test-method status="SKIP" signature="beforeFollowStatus(java.lang.String, java.lang.String)[pri:0, instance:testcases.TestFollow@546ccad7]" name="beforeFollowStatus" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeFollowStatus -->
        <test-method status="SKIP" signature="follow(java.lang.String, java.lang.String)[pri:1, instance:testcases.TestFollow@546ccad7]" name="follow" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- follow -->
        <test-method status="SKIP" signature="afterFollowStatus(java.lang.String, java.lang.String)[pri:2, instance:testcases.TestFollow@546ccad7]" name="afterFollowStatus" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterFollowStatus -->
        <test-method status="SKIP" signature="alreadyFollow(java.lang.String, java.lang.String)[pri:3, instance:testcases.TestFollow@546ccad7]" name="alreadyFollow" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alreadyFollow -->
        <test-method status="SKIP" signature="following(java.lang.String, java.lang.String)[pri:4, instance:testcases.TestFollow@546ccad7]" name="following" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- following -->
        <test-method status="SKIP" signature="follower(java.lang.String, java.lang.String)[pri:5, instance:testcases.TestFollow@546ccad7]" name="follower" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- follower -->
        <test-method status="SKIP" signature="followerTokenUser(java.lang.String, java.lang.String)[pri:5, instance:testcases.TestFollow@546ccad7]" name="followerTokenUser" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- followerTokenUser -->
        <test-method status="SKIP" signature="followerTokenVisitor(java.lang.String, java.lang.String)[pri:5, instance:testcases.TestFollow@546ccad7]" name="followerTokenVisitor" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- followerTokenVisitor -->
        <test-method status="SKIP" signature="Unfollow(java.lang.String, java.lang.String)[pri:6, instance:testcases.TestFollow@546ccad7]" name="Unfollow" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Unfollow -->
        <test-method status="SKIP" signature="alreadyUnfollow(java.lang.String, java.lang.String)[pri:7, instance:testcases.TestFollow@546ccad7]" name="alreadyUnfollow" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alreadyUnfollow -->
        <test-method status="SKIP" signature="followSelf(java.lang.String, java.lang.String)[pri:8, instance:testcases.TestFollow@546ccad7]" name="followSelf" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- followSelf -->
        <test-method status="SKIP" signature="followWithoutToken(java.lang.String, java.lang.String)[pri:9, instance:testcases.TestFollow@546ccad7]" name="followWithoutToken" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- followWithoutToken -->
        <test-method status="SKIP" signature="followWithVisitorToken(java.lang.String, java.lang.String)[pri:10, instance:testcases.TestFollow@546ccad7]" name="followWithVisitorToken" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- followWithVisitorToken -->
        <test-method status="SKIP" signature="unfollowWithoutToken(java.lang.String, java.lang.String)[pri:11, instance:testcases.TestFollow@546ccad7]" name="unfollowWithoutToken" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unfollowWithoutToken -->
        <test-method status="SKIP" signature="unfollowWithVisitorToken(java.lang.String, java.lang.String)[pri:12, instance:testcases.TestFollow@546ccad7]" name="unfollowWithVisitorToken" duration-ms="0" started-at="2020-09-29T15:47:22Z" data-provider="TargetUserFollowUnfollow" finished-at="2020-09-29T15:47:22Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.FileNotFoundException: ..\api-hot\src\test\java\com\test\api\datatest\data.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utility.ReadExcel.getCellData(ReadExcel.java:15)
	at testcases.TestFollow.TargetUserFollowUnfollow(TestFollow.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unfollowWithVisitorToken -->
      </class> <!-- testcases.TestFollow -->
      <class name="testcases.TestViews">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestViews@3a62c01e]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:44:41Z" finished-at="2020-09-29T15:44:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="viewWithLogin()[pri:0, instance:testcases.TestViews@3a62c01e]" name="viewWithLogin" duration-ms="15343" started-at="2020-09-29T15:44:41Z" finished-at="2020-09-29T15:44:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewWithLogin -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestViews@3a62c01e]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:44:57Z" finished-at="2020-09-29T15:44:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestViews@3a62c01e]" name="set" is-config="true" duration-ms="3" started-at="2020-09-29T15:44:57Z" finished-at="2020-09-29T15:44:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="getViewWithLogin()[pri:1, instance:testcases.TestViews@3a62c01e]" name="getViewWithLogin" duration-ms="17493" started-at="2020-09-29T15:44:57Z" finished-at="2020-09-29T15:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getViewWithLogin -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestViews@3a62c01e]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:45:14Z" finished-at="2020-09-29T15:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestViews -->
      <class name="testcases.TestLike">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:42:19Z" finished-at="2020-09-29T15:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="like()[pri:0, instance:testcases.TestLike@3c435123]" name="like" duration-ms="22310" started-at="2020-09-29T15:42:19Z" finished-at="2020-09-29T15:42:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- like -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:42:42Z" finished-at="2020-09-29T15:42:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="1" started-at="2020-09-29T15:42:42Z" finished-at="2020-09-29T15:42:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="likeAlready()[pri:1, instance:testcases.TestLike@3c435123]" name="likeAlready" duration-ms="19682" started-at="2020-09-29T15:42:42Z" finished-at="2020-09-29T15:43:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- likeAlready -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:43:01Z" finished-at="2020-09-29T15:43:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="1" started-at="2020-09-29T15:43:01Z" finished-at="2020-09-29T15:43:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="unlike()[pri:2, instance:testcases.TestLike@3c435123]" name="unlike" duration-ms="18822" started-at="2020-09-29T15:43:01Z" finished-at="2020-09-29T15:43:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unlike -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:43:20Z" finished-at="2020-09-29T15:43:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:43:20Z" finished-at="2020-09-29T15:43:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="unlikeAlready()[pri:3, instance:testcases.TestLike@3c435123]" name="unlikeAlready" duration-ms="17978" started-at="2020-09-29T15:43:20Z" finished-at="2020-09-29T15:43:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unlikeAlready -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:43:38Z" finished-at="2020-09-29T15:43:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:43:38Z" finished-at="2020-09-29T15:43:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="likeWithoutToken()[pri:4, instance:testcases.TestLike@3c435123]" name="likeWithoutToken" duration-ms="14912" started-at="2020-09-29T15:43:38Z" finished-at="2020-09-29T15:43:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- likeWithoutToken -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="5" started-at="2020-09-29T15:43:53Z" finished-at="2020-09-29T15:43:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="3" started-at="2020-09-29T15:43:53Z" finished-at="2020-09-29T15:43:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="likeWithTokenVisitor()[pri:5, instance:testcases.TestLike@3c435123]" name="likeWithTokenVisitor" duration-ms="15469" started-at="2020-09-29T15:43:53Z" finished-at="2020-09-29T15:44:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- likeWithTokenVisitor -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="4" started-at="2020-09-29T15:44:09Z" finished-at="2020-09-29T15:44:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:44:09Z" finished-at="2020-09-29T15:44:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="unlikeWithoutToken()[pri:6, instance:testcases.TestLike@3c435123]" name="unlikeWithoutToken" duration-ms="12363" started-at="2020-09-29T15:44:09Z" finished-at="2020-09-29T15:44:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unlikeWithoutToken -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:44:21Z" finished-at="2020-09-29T15:44:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestLike@3c435123]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:44:21Z" finished-at="2020-09-29T15:44:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="unlikeWithTokenVisitor()[pri:7, instance:testcases.TestLike@3c435123]" name="unlikeWithTokenVisitor" duration-ms="12970" started-at="2020-09-29T15:44:21Z" finished-at="2020-09-29T15:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unlikeWithTokenVisitor -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestLike@3c435123]" name="down" is-config="true" duration-ms="2" started-at="2020-09-29T15:44:34Z" finished-at="2020-09-29T15:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestLike -->
      <class name="testcases.TestVoteCompetition">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:45:14Z" finished-at="2020-09-29T15:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="getQuota()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="getQuota" duration-ms="14653" started-at="2020-09-29T15:45:14Z" finished-at="2020-09-29T15:45:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getQuota -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:45:29Z" finished-at="2020-09-29T15:45:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="set" is-config="true" duration-ms="1" started-at="2020-09-29T15:45:29Z" finished-at="2020-09-29T15:45:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="postVote()[pri:1, instance:testcases.TestVoteCompetition@7a8fa663]" name="postVote" duration-ms="24740" started-at="2020-09-29T15:45:29Z" finished-at="2020-09-29T15:45:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postVote -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="down" is-config="true" duration-ms="3" started-at="2020-09-29T15:45:54Z" finished-at="2020-09-29T15:45:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:45:54Z" finished-at="2020-09-29T15:45:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="postVoteLebih()[pri:2, instance:testcases.TestVoteCompetition@7a8fa663]" name="postVoteLebih" duration-ms="21822" started-at="2020-09-29T15:45:54Z" finished-at="2020-09-29T15:46:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postVoteLebih -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:46:15Z" finished-at="2020-09-29T15:46:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="set" is-config="true" duration-ms="2" started-at="2020-09-29T15:46:15Z" finished-at="2020-09-29T15:46:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="FAIL" signature="postVoteNullQuota()[pri:2, instance:testcases.TestVoteCompetition@7a8fa663]" name="postVoteNullQuota" duration-ms="20795" started-at="2020-09-29T15:46:15Z" finished-at="2020-09-29T15:46:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> but was <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:494)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1750)
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1755)
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:175)
	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
	at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:259)
	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
	at function.Validation.postBody(Validation.java:60)
	at testcases.TestVoteCompetition.postVoteNullQuota(TestVoteCompetition.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postVoteNullQuota -->
        <test-method status="PASS" signature="down()[pri:0, instance:testcases.TestVoteCompetition@7a8fa663]" name="down" is-config="true" duration-ms="1" started-at="2020-09-29T15:46:36Z" finished-at="2020-09-29T15:46:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- testcases.TestVoteCompetition -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
